spring:
  application:
    name: gymbuddy-training
  jpa:
    hibernate:
      ddl-auto: validate
      show_sql: true
      format_sql: true
    defer-datasource-initialization: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/gymbuddy
    username: ${DB_USER}
    password: ${DB_PWD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  mvc:
    format:
      date-time: iso

server:
  port: 8080