spring:
  application:
    name: gymbuddy-training
  jpa:
    hibernate:
      ddl-auto: create-drop
      show_sql: true
      format_sql: true
    defer-datasource-initialization: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/gymbuddy
    username: ${DB_USER}
    password: ${DB_PWD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  mvc:
    format:
      date-time: iso

mybatis:
  mapper-locations: "query/queries.xml"
  configuration:
    map-underscore-to-camel-case: true

firebase:
  audience: gymbuddy-b4e20
  issuer: https://securetoken.google.com/gymbuddy-b4e20
  public-key-provider: "https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com"

server:
  port: 8080